# Generated by Django 2.2.14 on 2020-10-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_based',
            field=models.BooleanField(default=False),
        ),
    ]
