# Generated by Django 2.2.14 on 2020-10-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_tasklist_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.Company'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
