# Generated by Django 2.2.14 on 2020-10-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20201009_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='credits_comsumed',
            field=models.FloatField(blank=True, null=True, verbose_name='Credits Comsumed'),
        ),
    ]
